
workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 10
    environment:
      vars:
        JAVA_VERSION: 17
    scripts:
      - ./gradlew clean
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
