
workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 10
    environment:
      android:
        sdk: "34"
    scripts:
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
